//! Low-level FFI bindings to the [CGNS](https://cgns.org) C library.
//!
//! CGNS (CFD General Notation System) is a standard for storing and retrieving
//! computational fluid dynamics (CFD) data. It is the ISO 10303-209 standard
//! and uses HDF5 as its underlying storage layer.
//!
//! # Architecture
//!
//! This crate provides **raw `extern "C"` bindings** generated by
//! [`bindgen`](https://rust-lang.github.io/rust-bindgen/).  Every CGNS
//! Mid-Level Library (MLL) function is available as an `unsafe` Rust
//! function.  The CGNS source is compiled from a git submodule
//! (`vendor/cgns`, tag `v4.5.2`), and HDF5 is automatically downloaded
//! and built as a static library during the build.
//!
//! All 300+ CGNS functions, types, and constants are in this module.
//! See [`CGNS_ENUMT`](https://cgns.github.io/CGNS_docs_current/midlevel/index.html)
//! for the official API reference.
//!
//! # Build
//!
//! The [`build.rs`](https://doc.rust-lang.org/cargo/reference/build-scripts.html)
//! performs three steps:
//!
//! 1. **HDF5** – Downloads HDF5 `1.14.6` source and compiles it as a static
//!    library via CMake (no tools, no Fortran, no compression libs).
//! 2. **CGNS** – Compiles the vendored CGNS source via CMake with HDF5
//!    support enabled, producing `libcgns.a`.
//! 3. **bindgen** – Parses `cgnslib.h` and generates `bindings.rs` into
//!    `$OUT_DIR`.
//!
//! ## Prerequisites
//!
//! - CMake >= 3.20
//! - A C compiler (gcc, clang, MSVC)
//! - `curl` and `tar` (for downloading / extracting HDF5)
//!
//! ## Environment variables
//!
//! | Variable | Purpose |
//! |---|---|
//! | `HDF5_DIR` | Path to pre-built HDF5 installation (skips the download+build step) |
//! | `CGNS_RS_NO_BUILD_HDF5` | Set to `1` to force-skip the HDF5 build (must also set `HDF5_DIR`) |
//!
//! # Updating CGNS
//!
//! 1. Update the git submodule:
//!    `git -C cgns-sys/vendor/cgns fetch --tags`
//!    `git -C cgns-sys/vendor/cgns checkout <new-tag>`
//! 2. Update the HDF5 version in `build.rs` if needed.
//! 3. Rebuild – `bindgen` automatically re-runs on any CGNS header change.
//!
//! # Safety
//!
//! All CGNS functions are `unsafe`:
//!
//! - They may read/write arbitrary memory through raw pointers.
//! - You must ensure buffers are large enough and properly aligned.
//! - File handles returned by `cg_open` must be valid when passed to other
//!   CGNS functions.
//! - Strings passed to CGNS must be valid null-terminated C strings.
//!
//! Use the high-level [`cgns`](../cgns/index.html) crate for a safe,
//! idiomatic Rust API.
//!
//! # Quick start
//!
//! ```
//! use std::ffi::CString;
//!
//! // File handle (filled by cg_open)
//! let mut fn_ = 0i32;
//!
//! unsafe {
//!     let fname = CString::new("test.cgns").unwrap();
//!     let status = cgns_sys::cg_open(
//!         fname.as_ptr(),
//!         cgns_sys::CG_MODE_WRITE as i32,
//!         &mut fn_,
//!     );
//!     assert_eq!(status, cgns_sys::CG_OK as i32);
//!
//!     // ... write data ...
//!
//!     cgns_sys::cg_close(fn_);
//! }
//! ```
//!
//! # Safe wrappers
//!
//! This crate provides **safe, idiomatic Rust wrappers** for a subset of CGNS
//! operations.  All wrappers acquire the global [`CGNS_MUTEX`] before calling
//! into the C library (which is **not thread-safe**).  The following wrappers
//! are currently implemented:
//!
//! | Category | Wrapper | CGNS function |
//! |---|---|---|
//! | File I/O | [`open_write`] | `cg_open` + `cg_set_file_type` |
//! | File I/O | [`open_read`] | `cg_open` |
//! | File I/O | [`close`] | `cg_close` |
//! | Bases | [`base_write`] | `cg_base_write` |
//! | Zones (structured) | [`zone_write_structured`] | `cg_zone_write` |
//! | Coordinates | [`coord_write`] | `cg_coord_write` |
//! | Coordinates | [`coord_read`] | `cg_coord_read` |
//! | Solutions | [`sol_write`] | `cg_sol_write` |
//! | Fields | [`field_write`] | `cg_field_write` |
//! | Fields | [`field_read`] | `cg_field_read` |
//! | Utilities | [`error_message`] | `cg_get_error` |
//! | Utilities | [`status_to_result`] | (conversion helper) |
//! | Utilities | [`lock_cgns`] | (CGNS mutex guard) |
//! | Utilities | [`ensure_hdf5_backend`] | `cg_set_file_type` |
//!
//! ## Missing wrappers (planned / needed)
//!
//! These CGNS function groups are only accessible through raw `unsafe` FFI
//! calls for now:
//!
//! | Group | Priority | Notes |
//! |---|---|---|
//! | `open_modify` (`CG_MODE_MODIFY`) | high | Append to an existing file |
//! | Unstructured zones | [`zone_write_unstructured`] | `cg_zone_write` (with `Unstructured`) |
//! | Sections | [`section_write`] | `cg_section_write` |
//! | Sections | [`nsections`] | `cg_nsections` |
//! | Elements | [`element_data_size`] | `cg_ElementDataSize` |
//! | Elements | [`elements_read`] | `cg_elements_read` |
//! | `cg_boco_*` | high | Boundary conditions |
//! | `cg_conn_*` / `cg_1to1_*` | medium | Zone connectivity |
//! | `cg_family_*` | medium | Family definitions |
//! | `cg_array_*` | medium | Raw array read/write |
//! | `cg_grid_*` | medium | Grid connectivity |
//! | `cg_goto` / `cg_gorel` | low | Legacy tree navigation |
//! | `cg_biter_write` / timestep iter | low | Unsteady data |
//! | `cgp_*` | low | Parallel CGNS |
//!
//! All 300+ raw functions are available directly (e.g. `unsafe { cgns_sys::cg_nbases(...) }`).
//! See the [official CGNS MLL reference](https://cgns.github.io/CGNS_docs_current/midlevel/index.html)
//! for the complete API.
//!
//! # Thread safety
//!
//! The CGNS C library uses global state for file type, error messages, and
//! internal I/O buffers — it is **not thread-safe**.  This crate serialises
//! all FFI calls through a global [`std::sync::Mutex`] (`CGNS_MUTEX`).
//! Every safe wrapper acquires the lock, so concurrent access from multiple
//! threads is safe.
//!
//! If you call raw FFI functions directly, you **must** acquire the lock
//! yourself via [`lock_cgns`] to avoid data races.
//!
//! # Quick start
//!
//! ```no_run
//! use cgns_sys::*;
//!
//! // Write
//! let fn_ = open_write("output.cgns").unwrap();
//! let base = base_write(fn_, "Base", 3, 3).unwrap();
//! let zone = zone_write_structured(fn_, base, "Zone", &[4,3,5, 3,2,4, 0,0,0]).unwrap();
//! let _coord = coord_write(fn_, base, zone, DataType_t_RealDouble, "X", &[0.0; 60]).unwrap();
//! close(fn_).unwrap();
//!
//! // Read
//! let fn_ = open_read("output.cgns").unwrap();
//! let mut buf = vec![0.0; 60];
//! coord_read(fn_, 1, 1, DataType_t_RealDouble, "X", &[1,1,1], &[4,3,5], &mut buf).unwrap();
//! close(fn_).unwrap();
//! ```

// Generated code may use non-Rust naming conventions.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ---------------------------------------------------------------------------
// Safe helper utilities
// ---------------------------------------------------------------------------

/// Return the last CGNS error message as a `String`.
///
/// CGNS stores a thread-local error string that you can retrieve after a
/// failed call.  This function wraps [`cg_get_error`] safely.
///
/// # Examples
///
/// ```
/// let msg = cgns_sys::error_message();
/// // msg is either a description or "unknown CGNS error"
/// ```
pub fn error_message() -> String {
    unsafe {
        let ptr = cg_get_error();
        if ptr.is_null() {
            "unknown CGNS error".to_string()
        } else {
            std::ffi::CStr::from_ptr(ptr).to_string_lossy().into_owned()
        }
    }
}

/// Convert a CGNS return code to `Result<(), &str>`.
///
/// CGNS functions return `CG_OK` (0) on success or an error code on failure.
/// This helper converts those codes into a Rust `Result`.
///
/// # Examples
///
/// ```
/// let status = cgns_sys::CG_OK as i32;
/// assert!(cgns_sys::status_to_result(status).is_ok());
/// ```
pub fn status_to_result(status: i32) -> Result<(), String> {
    if status == CG_OK as i32 {
        Ok(())
    } else {
        Err(error_message())
    }
}

/// Global CGNS mutex.
///
/// The CGNS C library is **not thread-safe** — it uses global state for file
/// type, error messages, and tree navigation.  This mutex serialises all
/// FFI calls so that safe Rust wrappers can be used from multiple threads.
static CGNS_MUTEX: std::sync::Mutex<()> = std::sync::Mutex::new(());

/// Acquire the global CGNS lock (publicly visible so callers who bypass the
/// safe wrappers can still serialise access).
///
/// Returns `Err` if the mutex is poisoned (a previous thread panicked while
/// holding it).  Callers should propagate this with `?`.
pub fn lock_cgns() -> Result<std::sync::MutexGuard<'static, ()>, String> {
    CGNS_MUTEX
        .lock()
        .map_err(|e| format!("CGNS mutex poisoned: {e}"))
}

/// Ensure the CGNS library uses HDF5 as its file backend.
///
/// This is called by [`open_write`] before every write-open.
/// Calling it multiple times is harmless.
pub fn ensure_hdf5_backend() {
    unsafe {
        cg_set_file_type(CG_FILE_HDF5 as i32);
    }
}

// ---------------------------------------------------------------------------
// Code-generation macros for repetitive wrapper patterns
// ---------------------------------------------------------------------------

/// Generate a "count" function (e.g. `nbases`, `nzones`, `nsols`).
macro_rules! impl_n_fn {
    ($name:ident, $c_func:ident, ($($param:ident: $ptype:ty),*)) => {
        pub fn $name($($param: $ptype,)*) -> Result<i32, String> {
            let _guard = lock_cgns()?;
            let mut n: i32 = 0;
            let status = unsafe { $c_func($($param,)* &mut n) };
            status_to_result(status).map(|_| n)
        }
    };
}

/// Generate an `i64`-returning count function (e.g. `element_data_size`).
macro_rules! impl_n_fn_i64 {
    ($name:ident, $c_func:ident, ($($param:ident: $ptype:ty),*)) => {
        pub fn $name($($param: $ptype,)*) -> Result<i64, String> {
            let _guard = lock_cgns()?;
            let mut n: i64 = 0;
            let status = unsafe { $c_func($($param,)* &mut n) };
            status_to_result(status).map(|_| n)
        }
    };
}

/// Generate a typed `coord_write_*` variant.
macro_rules! impl_coord_write_typed {
    ($name:ident, $ty:ty, $data_type:ident) => {
        pub fn $name(
            fn_: i32,
            base: i32,
            zone: i32,
            name: &str,
            data: &[$ty],
        ) -> Result<i32, String> {
            let _guard = lock_cgns()?;
            let c_name = std::ffi::CString::new(name)
                .map_err(|e| format!("invalid coordinate name: {}", e))?;
            let mut coord_idx: i32 = 0;
            let status = unsafe {
                cg_coord_write(
                    fn_,
                    base,
                    zone,
                    $data_type,
                    c_name.as_ptr(),
                    data.as_ptr() as *const std::ffi::c_void,
                    &mut coord_idx,
                )
            };
            status_to_result(status).map(|_| coord_idx)
        }
    };
}

/// Generate a typed `coord_read_*` variant.
macro_rules! impl_coord_read_typed {
    ($name:ident, $ty:ty, $data_type:ident) => {
        #[allow(clippy::too_many_arguments)]
        pub fn $name(
            fn_: i32,
            base: i32,
            zone: i32,
            name: &str,
            rmin: &[i64],
            rmax: &[i64],
            data: &mut [$ty],
        ) -> Result<(), String> {
            let _guard = lock_cgns()?;
            let c_name = std::ffi::CString::new(name)
                .map_err(|e| format!("invalid coordinate name: {}", e))?;
            let status = unsafe {
                cg_coord_read(
                    fn_,
                    base,
                    zone,
                    c_name.as_ptr(),
                    $data_type,
                    rmin.as_ptr(),
                    rmax.as_ptr(),
                    data.as_mut_ptr() as *mut std::ffi::c_void,
                )
            };
            status_to_result(status)
        }
    };
}

/// Generate a typed `field_write_*` variant.
macro_rules! impl_field_write_typed {
    ($name:ident, $ty:ty, $data_type:ident) => {
        pub fn $name(
            fn_: i32,
            base: i32,
            zone: i32,
            sol: i32,
            name: &str,
            data: &[$ty],
        ) -> Result<i32, String> {
            let _guard = lock_cgns()?;
            let c_name =
                std::ffi::CString::new(name).map_err(|e| format!("invalid field name: {}", e))?;
            let mut field: i32 = 0;
            let status = unsafe {
                cg_field_write(
                    fn_,
                    base,
                    zone,
                    sol,
                    $data_type,
                    c_name.as_ptr(),
                    data.as_ptr() as *const std::ffi::c_void,
                    &mut field,
                )
            };
            status_to_result(status).map(|_| field)
        }
    };
}

/// Generate a typed `field_read_*` variant.
macro_rules! impl_field_read_typed {
    ($name:ident, $ty:ty, $data_type:ident) => {
        #[allow(clippy::too_many_arguments)]
        pub fn $name(
            fn_: i32,
            base: i32,
            zone: i32,
            sol: i32,
            name: &str,
            rmin: &[i64],
            rmax: &[i64],
            data: &mut [$ty],
        ) -> Result<(), String> {
            let _guard = lock_cgns()?;
            let c_name =
                std::ffi::CString::new(name).map_err(|e| format!("invalid field name: {}", e))?;
            let status = unsafe {
                cg_field_read(
                    fn_,
                    base,
                    zone,
                    sol,
                    c_name.as_ptr(),
                    $data_type,
                    rmin.as_ptr(),
                    rmax.as_ptr(),
                    data.as_mut_ptr() as *mut std::ffi::c_void,
                )
            };
            status_to_result(status)
        }
    };
}

/// Open a CGNS file for writing (create).
///
/// This is a safe wrapper around [`cg_open`] with `CG_MODE_WRITE`.
/// The HDF5 backend is initialized once on the first call.
/// Returns the CGNS file number on success.
///
/// # Panics
///
/// Panics if the filename contains a null byte.
pub fn open_write(filename: &str) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    ensure_hdf5_backend();
    let c_filename =
        std::ffi::CString::new(filename).map_err(|e| format!("invalid filename: {}", e))?;
    let mut fn_: i32 = 0;
    let status = unsafe { cg_open(c_filename.as_ptr(), CG_MODE_WRITE as i32, &mut fn_) };
    status_to_result(status).map(|_| fn_)
}

/// Open a CGNS file for reading.
///
/// Returns the CGNS file number on success.
pub fn open_read(filename: &str) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_filename =
        std::ffi::CString::new(filename).map_err(|e| format!("invalid filename: {}", e))?;
    let mut fn_: i32 = 0;
    let status = unsafe { cg_open(c_filename.as_ptr(), CG_MODE_READ as i32, &mut fn_) };
    status_to_result(status).map(|_| fn_)
}

/// Open a CGNS file for modification (append).
///
/// Opens an existing file and allows appending new data without
/// overwriting existing content.
pub fn open_modify(filename: &str) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_filename =
        std::ffi::CString::new(filename).map_err(|e| format!("invalid filename: {}", e))?;
    let mut fn_: i32 = 0;
    let status = unsafe { cg_open(c_filename.as_ptr(), CG_MODE_MODIFY as i32, &mut fn_) };
    status_to_result(status).map(|_| fn_)
}

impl_n_fn!(nbocos, cg_nbocos, (fn_: i32, base: i32, zone: i32));

/// Write a boundary condition.
#[allow(clippy::too_many_arguments)]
pub fn boco_write(
    fn_: i32,
    base: i32,
    zone: i32,
    name: &str,
    bocotype: u32,
    ptset_type: u32,
    npnts: i64,
    pnts: &[i64],
) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name = std::ffi::CString::new(name).map_err(|e| format!("invalid BC name: {}", e))?;
    let mut bc: i32 = 0;
    let status = unsafe {
        cg_boco_write(
            fn_,
            base,
            zone,
            c_name.as_ptr(),
            bocotype,
            ptset_type,
            npnts,
            pnts.as_ptr(),
            &mut bc,
        )
    };
    status_to_result(status).map(|_| bc)
}

/// Read boundary condition metadata.
#[allow(clippy::too_many_arguments)]
pub fn boco_info(
    fn_: i32,
    base: i32,
    zone: i32,
    bc: i32,
    name: &mut [u8],
    bocotype: &mut u32,
    ptset_type: &mut u32,
    npnts: &mut i64,
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let mut normal_index: i32 = 0;
    let mut normal_list_size: i64 = 0;
    let mut normal_data_type: u32 = 0;
    let mut ndataset: i32 = 0;
    let status = unsafe {
        cg_boco_info(
            fn_,
            base,
            zone,
            bc,
            name.as_mut_ptr() as *mut i8,
            bocotype as *mut u32,
            ptset_type as *mut u32,
            npnts as *mut i64,
            &mut normal_index,
            &mut normal_list_size,
            &mut normal_data_type,
            &mut ndataset,
        )
    };
    status_to_result(status)
}

/// Read boundary condition point data.
///
/// `pnts` must be pre-allocated to the correct size (retrieved via [`boco_info`]).
pub fn boco_read(fn_: i32, base: i32, zone: i32, bc: i32, pnts: &mut [i64]) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status =
        unsafe { cg_boco_read(fn_, base, zone, bc, pnts.as_mut_ptr(), std::ptr::null_mut()) };
    status_to_result(status)
}

impl_n_fn!(n1to1, cg_n1to1, (fn_: i32, base: i32, zone: i32));

/// Write a 1-to-1 zone interface.
#[allow(clippy::too_many_arguments)]
pub fn write_1to1(
    fn_: i32,
    base: i32,
    zone: i32,
    name: &str,
    donor_name: &str,
    range: &[i64],
    donor_range: &[i64],
    transform: &[i32],
) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name = std::ffi::CString::new(name).map_err(|e| format!("invalid name: {}", e))?;
    let c_donor =
        std::ffi::CString::new(donor_name).map_err(|e| format!("invalid donor name: {}", e))?;
    let mut idx: i32 = 0;
    let status = unsafe {
        cg_1to1_write(
            fn_,
            base,
            zone,
            c_name.as_ptr(),
            c_donor.as_ptr(),
            range.as_ptr(),
            donor_range.as_ptr(),
            transform.as_ptr(),
            &mut idx,
        )
    };
    status_to_result(status).map(|_| idx)
}

/// Read a 1-to-1 zone interface.
#[allow(clippy::too_many_arguments)]
pub fn read_1to1(
    fn_: i32,
    base: i32,
    zone: i32,
    conn: i32,
    name: &mut [u8],
    donor_name: &mut [u8],
    range: &mut [i64],
    donor_range: &mut [i64],
    transform: &mut [i32],
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe {
        cg_1to1_read(
            fn_,
            base,
            zone,
            conn,
            name.as_mut_ptr() as *mut i8,
            donor_name.as_mut_ptr() as *mut i8,
            range.as_mut_ptr(),
            donor_range.as_mut_ptr(),
            transform.as_mut_ptr(),
        )
    };
    status_to_result(status)
}

impl_n_fn!(nconns, cg_nconns, (fn_: i32, base: i32, zone: i32));

/// Read general connectivity info.
#[allow(clippy::too_many_arguments)]
pub fn conn_info(
    fn_: i32,
    base: i32,
    zone: i32,
    conn: i32,
    name: &mut [u8],
    location: &mut u32,
    connect_type: &mut u32,
    ptset_type: &mut u32,
    npnts: &mut i64,
    donor_name: &mut [u8],
    donor_zonetype: &mut u32,
    donor_ptset_type: &mut u32,
    donor_datatype: &mut u32,
    ndata_donor: &mut i64,
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe {
        cg_conn_info(
            fn_,
            base,
            zone,
            conn,
            name.as_mut_ptr() as *mut i8,
            location as *mut u32,
            connect_type as *mut u32,
            ptset_type as *mut u32,
            npnts as *mut i64,
            donor_name.as_mut_ptr() as *mut i8,
            donor_zonetype as *mut u32,
            donor_ptset_type as *mut u32,
            donor_datatype as *mut u32,
            ndata_donor as *mut i64,
        )
    };
    status_to_result(status)
}

/// Read general connectivity point and donor data.
///
/// `points` and `donor_data` must be pre-allocated to the correct size.
pub fn conn_read(
    fn_: i32,
    base: i32,
    zone: i32,
    conn: i32,
    points: &mut [i64],
    donor_data: &mut [i64],
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe {
        cg_conn_read(
            fn_,
            base,
            zone,
            conn,
            points.as_mut_ptr(),
            DataType_t_Integer,
            donor_data.as_mut_ptr(),
        )
    };
    status_to_result(status)
}

/// Write a general (non-1-to-1) zone interface connection.
#[allow(clippy::too_many_arguments)]
pub fn conn_write(
    fn_: i32,
    base: i32,
    zone: i32,
    name: &str,
    location: u32,
    connect_type: u32,
    ptset_type: u32,
    npnts: i64,
    pnts: &[i64],
    donor_name: &str,
    donor_zonetype: u32,
    donor_ptset_type: u32,
    donor_datatype: u32,
    ndata_donor: i64,
    donor_data: &[i64],
) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name = std::ffi::CString::new(name).map_err(|e| format!("invalid name: {}", e))?;
    let c_donor =
        std::ffi::CString::new(donor_name).map_err(|e| format!("invalid donor name: {}", e))?;
    let mut idx: i32 = 0;
    let status = unsafe {
        cg_conn_write(
            fn_,
            base,
            zone,
            c_name.as_ptr(),
            location,
            connect_type,
            ptset_type,
            npnts,
            pnts.as_ptr(),
            c_donor.as_ptr(),
            donor_zonetype,
            donor_ptset_type,
            donor_datatype,
            ndata_donor,
            donor_data.as_ptr(),
            &mut idx,
        )
    };
    status_to_result(status).map(|_| idx)
}

impl_n_fn!(nfamilies, cg_nfamilies, (fn_: i32, base: i32));

/// Write a family.
pub fn family_write(fn_: i32, base: i32, name: &str) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name = std::ffi::CString::new(name).map_err(|e| format!("invalid family name: {}", e))?;
    let mut id: i32 = 0;
    let status = unsafe { cg_family_write(fn_, base, c_name.as_ptr(), &mut id) };
    status_to_result(status).map(|_| id)
}

/// Read a family name.
pub fn family_read(fn_: i32, base: i32, family: i32, name: &mut [u8]) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let mut nboco: i32 = 0;
    let mut ngeos: i32 = 0;
    let status = unsafe {
        cg_family_read(
            fn_,
            base,
            family,
            name.as_mut_ptr() as *mut i8,
            &mut nboco,
            &mut ngeos,
        )
    };
    status_to_result(status)
}

impl_n_fn!(nbases, cg_nbases, (fn_: i32));

/// Close a CGNS file.
pub fn close(fn_: i32) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe { cg_close(fn_) };
    status_to_result(status)
}

/// Read a CGNS base node (name, cell dimension, physical dimension).
pub fn base_read(
    fn_: i32,
    base: i32,
    name: &mut [u8],
    cell_dim: &mut i32,
    phys_dim: &mut i32,
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe {
        cg_base_read(
            fn_,
            base,
            name.as_mut_ptr() as *mut i8,
            cell_dim as *mut i32,
            phys_dim as *mut i32,
        )
    };
    status_to_result(status)
}

impl_n_fn!(nzones, cg_nzones, (fn_: i32, base: i32));

/// Return the cell dimension of a base.
pub fn cell_dim(fn_: i32, base: i32) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let mut dim: i32 = 0;
    let status = unsafe { cg_cell_dim(fn_, base, &mut dim) };
    status_to_result(status).map(|_| dim)
}

/// Write a CGNS base node.
pub fn base_write(fn_: i32, name: &str, cell_dim: i32, phys_dim: i32) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name = std::ffi::CString::new(name).map_err(|e| format!("invalid base name: {}", e))?;
    let mut base: i32 = 0;
    let status = unsafe { cg_base_write(fn_, c_name.as_ptr(), cell_dim, phys_dim, &mut base) };
    status_to_result(status).map(|_| base)
}

/// Write a structured zone.
pub fn zone_write_structured(fn_: i32, base: i32, name: &str, size: &[i64]) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name = std::ffi::CString::new(name).map_err(|e| format!("invalid zone name: {}", e))?;
    let mut zone: i32 = 0;
    let status = unsafe {
        cg_zone_write(
            fn_,
            base,
            c_name.as_ptr(),
            size.as_ptr(),
            ZoneType_t_Structured,
            &mut zone,
        )
    };
    status_to_result(status).map(|_| zone)
}

/// Write an unstructured zone section (element connectivity).
///
/// `elements` is the flat connectivity array (1-based node indices in
/// Fortran order).  Returns the section index on success.
#[allow(clippy::too_many_arguments)]
pub fn section_write(
    fn_: i32,
    base: i32,
    zone: i32,
    name: &str,
    elem_type: u32,
    start: i64,
    end: i64,
    nbndry: i32,
    elements: &[i64],
) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name =
        std::ffi::CString::new(name).map_err(|e| format!("invalid section name: {}", e))?;
    let mut section_idx: i32 = 0;
    let status = unsafe {
        cg_section_write(
            fn_,
            base,
            zone,
            c_name.as_ptr(),
            elem_type,
            start,
            end,
            nbndry,
            elements.as_ptr(),
            &mut section_idx,
        )
    };
    status_to_result(status).map(|_| section_idx)
}

impl_n_fn!(nsections, cg_nsections, (fn_: i32, base: i32, zone: i32));

impl_n_fn_i64!(element_data_size, cg_ElementDataSize, (fn_: i32, base: i32, zone: i32, section: i32));

/// Read a section's element connectivity.
///
/// `elements` must be pre-allocated to the correct size (retrieved via
/// [`element_data_size`]).
pub fn elements_read(
    fn_: i32,
    base: i32,
    zone: i32,
    section: i32,
    elements: &mut [i64],
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe {
        cg_elements_read(
            fn_,
            base,
            zone,
            section,
            elements.as_mut_ptr(),
            std::ptr::null_mut(),
        )
    };
    status_to_result(status)
}

/// Read a section's metadata.
#[allow(clippy::too_many_arguments)]
pub fn section_read(
    fn_: i32,
    base: i32,
    zone: i32,
    section: i32,
    name: &mut [u8],
    elem_type: &mut u32,
    start: &mut i64,
    end: &mut i64,
    nbound: &mut i32,
    parent_flag: &mut i32,
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe {
        cg_section_read(
            fn_,
            base,
            zone,
            section,
            name.as_mut_ptr() as *mut i8,
            elem_type as *mut u32,
            start as *mut i64,
            end as *mut i64,
            nbound as *mut i32,
            parent_flag as *mut i32,
        )
    };
    status_to_result(status)
}

/// Write an unstructured zone.
///
/// `size` must have 3 entries: `[num_vertices, num_elements, 0]`.
pub fn zone_write_unstructured(
    fn_: i32,
    base: i32,
    name: &str,
    size: &[i64],
) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name = std::ffi::CString::new(name).map_err(|e| format!("invalid zone name: {}", e))?;
    let mut zone: i32 = 0;
    let status = unsafe {
        cg_zone_write(
            fn_,
            base,
            c_name.as_ptr(),
            size.as_ptr(),
            ZoneType_t_Unstructured,
            &mut zone,
        )
    };
    status_to_result(status).map(|_| zone)
}

/// Read a zone's name and size.
///
/// `size` must be pre-allocated to the correct length (3 for structured,
/// as returned by [`index_dim`]).
pub fn zone_read(
    fn_: i32,
    base: i32,
    zone: i32,
    name: &mut [u8],
    size: &mut [i64],
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe {
        cg_zone_read(
            fn_,
            base,
            zone,
            name.as_mut_ptr() as *mut i8,
            size.as_mut_ptr(),
        )
    };
    status_to_result(status)
}

/// Return the index dimension of a zone.
pub fn index_dim(fn_: i32, base: i32, zone: i32) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let mut dim: i32 = 0;
    let status = unsafe { cg_index_dim(fn_, base, zone, &mut dim) };
    status_to_result(status).map(|_| dim)
}

/// Return the zone type.
pub fn zone_type(fn_: i32, base: i32, zone: i32) -> Result<u32, String> {
    let _guard = lock_cgns()?;
    let mut ztype: u32 = 0;
    let status = unsafe { cg_zone_type(fn_, base, zone, &mut ztype) };
    status_to_result(status).map(|_| ztype)
}

impl_n_fn!(ncoords, cg_ncoords, (fn_: i32, base: i32, zone: i32));

/// Read coordinate information (data type and name) for a coordinate index.
pub fn coord_info(
    fn_: i32,
    base: i32,
    zone: i32,
    coord: i32,
    data_type: &mut u32,
    name: &mut [u8],
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe {
        cg_coord_info(
            fn_,
            base,
            zone,
            coord,
            data_type as *mut u32,
            name.as_mut_ptr() as *mut i8,
        )
    };
    status_to_result(status)
}

/// Write grid coordinates for a structured zone.
///
/// `name` is the coordinate name (e.g. "CoordinateX") and `data` is a
/// contiguous slice of coordinate values.
pub fn coord_write(
    fn_: i32,
    base: i32,
    zone: i32,
    data_type: u32,
    name: &str,
    data: &[f64],
) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name =
        std::ffi::CString::new(name).map_err(|e| format!("invalid coordinate name: {}", e))?;
    let mut coord_idx: i32 = 0;
    let status = unsafe {
        cg_coord_write(
            fn_,
            base,
            zone,
            data_type,
            c_name.as_ptr(),
            data.as_ptr() as *const std::ffi::c_void,
            &mut coord_idx,
        )
    };
    status_to_result(status).map(|_| coord_idx)
}

impl_coord_write_typed!(coord_write_f32, f32, DataType_t_RealSingle);
impl_coord_write_typed!(coord_write_i32, i32, DataType_t_Integer);
impl_coord_write_typed!(coord_write_i64, i64, DataType_t_LongInteger);

/// Write a solution node.
pub fn sol_write(fn_: i32, base: i32, zone: i32, name: &str, location: u32) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name =
        std::ffi::CString::new(name).map_err(|e| format!("invalid solution name: {}", e))?;
    let mut sol: i32 = 0;
    let status = unsafe { cg_sol_write(fn_, base, zone, c_name.as_ptr(), location, &mut sol) };
    status_to_result(status).map(|_| sol)
}

impl_n_fn!(nsols, cg_nsols, (fn_: i32, base: i32, zone: i32));

/// Read solution info.
pub fn sol_info(
    fn_: i32,
    base: i32,
    zone: i32,
    sol: i32,
    name: &mut [u8],
    location: &mut u32,
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe {
        cg_sol_info(
            fn_,
            base,
            zone,
            sol,
            name.as_mut_ptr() as *mut i8,
            location as *mut u32,
        )
    };
    status_to_result(status)
}

impl_n_fn!(nfields, cg_nfields, (fn_: i32, base: i32, zone: i32, sol: i32));

/// Read field info (data type and name).
pub fn field_info(
    fn_: i32,
    base: i32,
    zone: i32,
    sol: i32,
    field: i32,
    data_type: &mut u32,
    name: &mut [u8],
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe {
        cg_field_info(
            fn_,
            base,
            zone,
            sol,
            field,
            data_type as *mut u32,
            name.as_mut_ptr() as *mut i8,
        )
    };
    status_to_result(status)
}

/// Write a flow solution field.
pub fn field_write(
    fn_: i32,
    base: i32,
    zone: i32,
    sol: i32,
    data_type: u32,
    name: &str,
    data: &[f64],
) -> Result<i32, String> {
    let _guard = lock_cgns()?;
    let c_name = std::ffi::CString::new(name).map_err(|e| format!("invalid field name: {}", e))?;
    let mut field: i32 = 0;
    let status = unsafe {
        cg_field_write(
            fn_,
            base,
            zone,
            sol,
            data_type,
            c_name.as_ptr(),
            data.as_ptr() as *const std::ffi::c_void,
            &mut field,
        )
    };
    status_to_result(status).map(|_| field)
}

impl_field_write_typed!(field_write_f32, f32, DataType_t_RealSingle);
impl_field_write_typed!(field_write_i32, i32, DataType_t_Integer);
impl_field_write_typed!(field_write_i64, i64, DataType_t_LongInteger);

/// Read grid coordinates for a structured zone.
///
/// `name` is the coordinate name (e.g. "CoordinateX") and `rmin` / `rmax`
/// specify the (1-based) index range to read.  The data is written into
/// the pre-allocated `data` slice.
#[allow(clippy::too_many_arguments)]
pub fn coord_read(
    fn_: i32,
    base: i32,
    zone: i32,
    data_type: u32,
    name: &str,
    rmin: &[i64],
    rmax: &[i64],
    data: &mut [f64],
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let c_name =
        std::ffi::CString::new(name).map_err(|e| format!("invalid coordinate name: {}", e))?;
    let status = unsafe {
        cg_coord_read(
            fn_,
            base,
            zone,
            c_name.as_ptr(),
            data_type,
            rmin.as_ptr(),
            rmax.as_ptr(),
            data.as_mut_ptr() as *mut std::ffi::c_void,
        )
    };
    status_to_result(status)
}

impl_coord_read_typed!(coord_read_f32, f32, DataType_t_RealSingle);
impl_coord_read_typed!(coord_read_i32, i32, DataType_t_Integer);
impl_coord_read_typed!(coord_read_i64, i64, DataType_t_LongInteger);

/// Read a flow solution field.
#[allow(clippy::too_many_arguments)]
pub fn field_read(
    fn_: i32,
    base: i32,
    zone: i32,
    sol: i32,
    data_type: u32,
    name: &str,
    rmin: &[i64],
    rmax: &[i64],
    data: &mut [f64],
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let c_name = std::ffi::CString::new(name).map_err(|e| format!("invalid field name: {}", e))?;
    let status = unsafe {
        cg_field_read(
            fn_,
            base,
            zone,
            sol,
            c_name.as_ptr(),
            data_type,
            rmin.as_ptr(),
            rmax.as_ptr(),
            data.as_mut_ptr() as *mut std::ffi::c_void,
        )
    };
    status_to_result(status)
}

impl_field_read_typed!(field_read_f32, f32, DataType_t_RealSingle);
impl_field_read_typed!(field_read_i32, i32, DataType_t_Integer);
impl_field_read_typed!(field_read_i64, i64, DataType_t_LongInteger);

// ---------------------------------------------------------------------------
// Base-level metadata wrappers: units, dataclass, simulation type
// ---------------------------------------------------------------------------

/// Write units at the current node (navigate there first with [`gopath`]).
pub fn units_write(
    mass: u32,
    length: u32,
    time: u32,
    temperature: u32,
    angle: u32,
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe { cg_units_write(mass, length, time, temperature, angle) };
    status_to_result(status)
}

/// Read units from the current node.
pub fn units_read(
    mass: &mut u32,
    length: &mut u32,
    time: &mut u32,
    temperature: &mut u32,
    angle: &mut u32,
) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe { cg_units_read(mass, length, time, temperature, angle) };
    status_to_result(status)
}

/// Write data class at the current node.
pub fn dataclass_write(dataclass: u32) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe { cg_dataclass_write(dataclass) };
    status_to_result(status)
}

/// Read data class from the current node.
pub fn dataclass_read(dataclass: &mut u32) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe { cg_dataclass_read(dataclass) };
    status_to_result(status)
}

/// Write simulation type for a base.
pub fn simulation_type_write(fn_: i32, base: i32, sim_type: u32) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe { cg_simulation_type_write(fn_, base, sim_type) };
    status_to_result(status)
}

/// Read simulation type from a base.
pub fn simulation_type_read(fn_: i32, base: i32, sim_type: &mut u32) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe { cg_simulation_type_read(fn_, base, sim_type) };
    status_to_result(status)
}

/// Navigate to a CGNS node by path.
///
/// The path uses Unix-style directory syntax (e.g. `/BaseName/ZoneName`).
pub fn gopath(fn_: i32, path: &str) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let c_path = std::ffi::CString::new(path).map_err(|e| format!("invalid path: {}", e))?;
    let status = unsafe { cg_gopath(fn_, c_path.as_ptr()) };
    status_to_result(status)
}

/// Query the CGNS file version.
pub fn version(fn_: i32, file_version: &mut f32) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let status = unsafe { cg_version(fn_, file_version as *mut f32) };
    status_to_result(status)
}

/// Save the CGNS file identified by `fn_` to `filename` with the given `file_type`.
///
/// `follow_links` controls whether symbolic links are followed (0 = no, 1 = yes).
pub fn save_as(fn_: i32, filename: &str, file_type: i32, follow_links: i32) -> Result<(), String> {
    let _guard = lock_cgns()?;
    let c_filename =
        std::ffi::CString::new(filename).map_err(|e| format!("invalid filename: {}", e))?;
    let status = unsafe { cg_save_as(fn_, c_filename.as_ptr(), file_type, follow_links) };
    status_to_result(status)
}
