//! Low-level FFI bindings to the [CGNS](https://cgns.org) C library.
//!
//! CGNS (CFD General Notation System) is a standard for storing and retrieving
//! computational fluid dynamics (CFD) data. It is the ISO 10303-209 standard
//! and uses HDF5 as its underlying storage layer.
//!
//! # Architecture
//!
//! This crate provides **raw `extern "C"` bindings** generated by
//! [`bindgen`](https://rust-lang.github.io/rust-bindgen/).  Every CGNS
//! Mid-Level Library (MLL) function is available as an `unsafe` Rust
//! function.  The CGNS source is compiled from a git submodule
//! (`vendor/cgns`, tag `v4.5.2`), and HDF5 is automatically downloaded
//! and built as a static library during the build.
//!
//! All 300+ CGNS functions, types, and constants are in this module.
//! See [`CGNS_ENUMT`](https://cgns.github.io/CGNS_docs_current/midlevel/index.html)
//! for the official API reference.
//!
//! # Build
//!
//! The [`build.rs`](https://doc.rust-lang.org/cargo/reference/build-scripts.html)
//! performs three steps:
//!
//! 1. **HDF5** – Downloads HDF5 `1.14.6` source and compiles it as a static
//!    library via CMake (no tools, no Fortran, no compression libs).
//! 2. **CGNS** – Compiles the vendored CGNS source via CMake with HDF5
//!    support enabled, producing `libcgns.a`.
//! 3. **bindgen** – Parses `cgnslib.h` and generates `bindings.rs` into
//!    `$OUT_DIR`.
//!
//! ## Prerequisites
//!
//! - CMake >= 3.20
//! - A C compiler (gcc, clang, MSVC)
//! - `curl` and `tar` (for downloading / extracting HDF5)
//!
//! ## Environment variables
//!
//! | Variable | Purpose |
//! |---|---|
//! | `HDF5_DIR` | Path to pre-built HDF5 installation (skips the download+build step) |
//! | `CGNS_RS_NO_BUILD_HDF5` | Set to `1` to force-skip the HDF5 build (must also set `HDF5_DIR`) |
//!
//! # Updating CGNS
//!
//! 1. Update the git submodule:  
//!    `git -C cgns-sys/vendor/cgns fetch --tags`  
//!    `git -C cgns-sys/vendor/cgns checkout <new-tag>`
//! 2. Update the HDF5 version in `build.rs` if needed.
//! 3. Rebuild – `bindgen` automatically re-runs on any CGNS header change.
//!
//! # Safety
//!
//! All CGNS functions are `unsafe`:
//!
//! - They may read/write arbitrary memory through raw pointers.
//! - You must ensure buffers are large enough and properly aligned.
//! - File handles returned by `cg_open` must be valid when passed to other
//!   CGNS functions.
//! - Strings passed to CGNS must be valid null-terminated C strings.
//!
//! Use the high-level [`cgns`](../cgns/index.html) crate for a safe,
//! idiomatic Rust API.
//!
//! # Quick start
//!
//! ```
//! use std::ffi::CString;
//!
//! // File handle (filled by cg_open)
//! let mut fn_ = 0i32;
//!
//! unsafe {
//!     let fname = CString::new("test.cgns").unwrap();
//!     let status = cgns_sys::cg_open(
//!         fname.as_ptr(),
//!         cgns_sys::CG_MODE_WRITE as i32,
//!         &mut fn_,
//!     );
//!     assert_eq!(status, cgns_sys::CG_OK as i32);
//!
//!     // ... write data ...
//!
//!     cgns_sys::cg_close(fn_);
//! }
//! ```
//!
//! # Safe wrappers
//!
//! This crate provides **safe, idiomatic Rust wrappers** for a subset of CGNS
//! operations.  All wrappers acquire the global [`CGNS_MUTEX`] before calling
//! into the C library (which is **not thread-safe**).  The following wrappers
//! are currently implemented:
//!
//! | Category | Wrapper | CGNS function |
//! |---|---|---|
//! | File I/O | [`open_write`] | `cg_open` + `cg_set_file_type` |
//! | File I/O | [`open_read`] | `cg_open` |
//! | File I/O | [`close`] | `cg_close` |
//! | Bases | [`base_write`] | `cg_base_write` |
//! | Zones (structured) | [`zone_write_structured`] | `cg_zone_write` |
//! | Coordinates | [`coord_write`] | `cg_coord_write` |
//! | Coordinates | [`coord_read`] | `cg_coord_read` |
//! | Solutions | [`sol_write`] | `cg_sol_write` |
//! | Fields | [`field_write`] | `cg_field_write` |
//! | Fields | [`field_read`] | `cg_field_read` |
//! | Utilities | [`error_message`] | `cg_get_error` |
//! | Utilities | [`status_to_result`] | (conversion helper) |
//! | Utilities | [`lock_cgns`] | (CGNS mutex guard) |
//! | Utilities | [`ensure_hdf5_backend`] | `cg_set_file_type` |
//!
//! ## Missing wrappers (planned / needed)
//!
//! These CGNS function groups are only accessible through raw `unsafe` FFI
//! calls for now:
//!
//! | Group | Priority | Notes |
//! |---|---|---|
//! | `open_modify` (`CG_MODE_MODIFY`) | high | Append to an existing file |
//! | `cg_section_*` / `cg_elements_*` | high | Unstructured grid support |
//! | `cg_boco_*` | high | Boundary conditions |
//! | `cg_conn_*` / `cg_1to1_*` | medium | Zone connectivity |
//! | `cg_family_*` | medium | Family definitions |
//! | `cg_array_*` | medium | Raw array read/write |
//! | `cg_grid_*` | medium | Grid connectivity |
//! | `cg_goto` / `cg_gorel` | low | Legacy tree navigation |
//! | `cg_biter_write` / timestep iter | low | Unsteady data |
//! | `cgp_*` | low | Parallel CGNS |
//!
//! All 300+ raw functions are available directly (e.g. `unsafe { cgns_sys::cg_nbases(...) }`).
//! See the [official CGNS MLL reference](https://cgns.github.io/CGNS_docs_current/midlevel/index.html)
//! for the complete API.
//!
//! # Thread safety
//!
//! The CGNS C library uses global state for file type, error messages, and
//! internal I/O buffers — it is **not thread-safe**.  This crate serialises
//! all FFI calls through a global [`std::sync::Mutex`] (`CGNS_MUTEX`).
//! Every safe wrapper acquires the lock, so concurrent access from multiple
//! threads is safe.
//!
//! If you call raw FFI functions directly, you **must** acquire the lock
//! yourself via [`lock_cgns`] to avoid data races.
//!
//! # Quick start
//!
//! ```no_run
//! use cgns_sys::*;
//!
//! // Write
//! let fn_ = open_write("output.cgns").unwrap();
//! let base = base_write(fn_, "Base", 3, 3).unwrap();
//! let zone = zone_write_structured(fn_, base, "Zone", &[4,3,5, 3,2,4, 0,0,0]).unwrap();
//! let _coord = coord_write(fn_, base, zone, DataType_t_RealDouble, "X", &[0.0; 60]).unwrap();
//! close(fn_).unwrap();
//!
//! // Read
//! let fn_ = open_read("output.cgns").unwrap();
//! let mut buf = vec![0.0; 60];
//! coord_read(fn_, 1, 1, DataType_t_RealDouble, "X", &[1,1,1], &[4,3,5], &mut buf).unwrap();
//! close(fn_).unwrap();
//! ```

// Generated code may use non-Rust naming conventions.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ---------------------------------------------------------------------------
// Safe helper utilities
// ---------------------------------------------------------------------------

/// Return the last CGNS error message as a `String`.
///
/// CGNS stores a thread-local error string that you can retrieve after a
/// failed call.  This function wraps [`cg_get_error`] safely.
///
/// # Examples
///
/// ```
/// let msg = cgns_sys::error_message();
/// // msg is either a description or "unknown CGNS error"
/// ```
pub fn error_message() -> String {
    unsafe {
        let ptr = cg_get_error();
        if ptr.is_null() {
            "unknown CGNS error".to_string()
        } else {
            std::ffi::CStr::from_ptr(ptr)
                .to_string_lossy()
                .into_owned()
        }
    }
}

/// Convert a CGNS return code to `Result<(), &str>`.
///
/// CGNS functions return `CG_OK` (0) on success or an error code on failure.
/// This helper converts those codes into a Rust `Result`.
///
/// # Examples
///
/// ```
/// let status = cgns_sys::CG_OK as i32;
/// assert!(cgns_sys::status_to_result(status).is_ok());
/// ```
pub fn status_to_result(status: i32) -> Result<(), String> {
    if status == CG_OK as i32 {
        Ok(())
    } else {
        Err(error_message())
    }
}

/// Global CGNS mutex.
///
/// The CGNS C library is **not thread-safe** — it uses global state for file
/// type, error messages, and tree navigation.  This mutex serialises all
/// FFI calls so that safe Rust wrappers can be used from multiple threads.
static CGNS_MUTEX: std::sync::Mutex<()> = std::sync::Mutex::new(());

/// Acquire the global CGNS lock (publicly visible so callers who bypass the
/// safe wrappers can still serialise access).
pub fn lock_cgns() -> std::sync::MutexGuard<'static, ()> {
    CGNS_MUTEX.lock().unwrap()
}

/// Ensure the CGNS library uses HDF5 as its file backend.
///
/// This is called (under the CGNS lock) by [`open_write`].
pub fn ensure_hdf5_backend() {
    static INIT: std::sync::Once = std::sync::Once::new();
    INIT.call_once(|| {
        unsafe {
            cg_set_file_type(CG_FILE_HDF5 as i32);
        }
    });
}

/// Open a CGNS file for writing (create).
///
/// This is a safe wrapper around [`cg_open`] with `CG_MODE_WRITE`.
/// The HDF5 backend is initialized once on the first call.
/// Returns the CGNS file number on success.
///
/// # Panics
///
/// Panics if the filename contains a null byte.
pub fn open_write(filename: &str) -> Result<i32, String> {
    let _guard = lock_cgns();
    ensure_hdf5_backend();
    let c_filename = std::ffi::CString::new(filename)
        .map_err(|e| format!("invalid filename: {}", e))?;
    let mut fn_: i32 = 0;
    let status = unsafe { cg_open(c_filename.as_ptr(), CG_MODE_WRITE as i32, &mut fn_) };
    status_to_result(status).map(|_| fn_)
}

/// Open a CGNS file for reading.
///
/// Returns the CGNS file number on success.
pub fn open_read(filename: &str) -> Result<i32, String> {
    let _guard = lock_cgns();
    let c_filename = std::ffi::CString::new(filename)
        .map_err(|e| format!("invalid filename: {}", e))?;
    let mut fn_: i32 = 0;
    let status = unsafe { cg_open(c_filename.as_ptr(), CG_MODE_READ as i32, &mut fn_) };
    status_to_result(status).map(|_| fn_)
}

/// Close a CGNS file.
pub fn close(fn_: i32) -> Result<(), String> {
    let _guard = lock_cgns();
    let status = unsafe { cg_close(fn_) };
    status_to_result(status)
}

/// Write a CGNS base node.
pub fn base_write(fn_: i32, name: &str, cell_dim: i32, phys_dim: i32) -> Result<i32, String> {
    let _guard = lock_cgns();
    let c_name = std::ffi::CString::new(name)
        .map_err(|e| format!("invalid base name: {}", e))?;
    let mut base: i32 = 0;
    let status = unsafe { cg_base_write(fn_, c_name.as_ptr(), cell_dim, phys_dim, &mut base) };
    status_to_result(status).map(|_| base)
}

/// Write a structured zone.
pub fn zone_write_structured(
    fn_: i32,
    base: i32,
    name: &str,
    size: &[i64],
) -> Result<i32, String> {
    let _guard = lock_cgns();
    let c_name = std::ffi::CString::new(name)
        .map_err(|e| format!("invalid zone name: {}", e))?;
    let mut zone: i32 = 0;
    let status = unsafe {
        cg_zone_write(
            fn_,
            base,
            c_name.as_ptr(),
            size.as_ptr(),
            ZoneType_t_Structured,
            &mut zone,
        )
    };
    status_to_result(status).map(|_| zone)
}

/// Write grid coordinates for a structured zone.
///
/// `name` is the coordinate name (e.g. "CoordinateX") and `data` is a
/// contiguous slice of coordinate values.
pub fn coord_write(
    fn_: i32,
    base: i32,
    zone: i32,
    data_type: u32,
    name: &str,
    data: &[f64],
) -> Result<i32, String> {
    let _guard = lock_cgns();
    let c_name = std::ffi::CString::new(name)
        .map_err(|e| format!("invalid coordinate name: {}", e))?;
    let mut coord_idx: i32 = 0;
    let status = unsafe {
        cg_coord_write(
            fn_,
            base,
            zone,
            data_type,
            c_name.as_ptr(),
            data.as_ptr() as *const std::ffi::c_void,
            &mut coord_idx,
        )
    };
    status_to_result(status).map(|_| coord_idx)
}

/// Write a solution node.
pub fn sol_write(
    fn_: i32,
    base: i32,
    zone: i32,
    name: &str,
    location: u32,
) -> Result<i32, String> {
    let _guard = lock_cgns();
    let c_name = std::ffi::CString::new(name)
        .map_err(|e| format!("invalid solution name: {}", e))?;
    let mut sol: i32 = 0;
    let status = unsafe {
        cg_sol_write(fn_, base, zone, c_name.as_ptr(), location, &mut sol)
    };
    status_to_result(status).map(|_| sol)
}

/// Write a flow solution field.
pub fn field_write(
    fn_: i32,
    base: i32,
    zone: i32,
    sol: i32,
    data_type: u32,
    name: &str,
    data: &[f64],
) -> Result<i32, String> {
    let _guard = lock_cgns();
    let c_name = std::ffi::CString::new(name)
        .map_err(|e| format!("invalid field name: {}", e))?;
    let mut field: i32 = 0;
    let status = unsafe {
        cg_field_write(
            fn_,
            base,
            zone,
            sol,
            data_type,
            c_name.as_ptr(),
            data.as_ptr() as *const std::ffi::c_void,
            &mut field,
        )
    };
    status_to_result(status).map(|_| field)
}

/// Read grid coordinates for a structured zone.
///
/// `name` is the coordinate name (e.g. "CoordinateX") and `rmin` / `rmax`
/// specify the (1-based) index range to read.  The data is written into
/// the pre-allocated `data` slice.
pub fn coord_read(
    fn_: i32,
    base: i32,
    zone: i32,
    data_type: u32,
    name: &str,
    rmin: &[i64],
    rmax: &[i64],
    data: &mut [f64],
) -> Result<(), String> {
    let _guard = lock_cgns();
    let c_name = std::ffi::CString::new(name)
        .map_err(|e| format!("invalid coordinate name: {}", e))?;
    let status = unsafe {
        cg_coord_read(
            fn_,
            base,
            zone,
            c_name.as_ptr(),
            data_type,
            rmin.as_ptr(),
            rmax.as_ptr(),
            data.as_mut_ptr() as *mut std::ffi::c_void,
        )
    };
    status_to_result(status)
}

/// Read a flow solution field.
pub fn field_read(
    fn_: i32,
    base: i32,
    zone: i32,
    sol: i32,
    data_type: u32,
    name: &str,
    rmin: &[i64],
    rmax: &[i64],
    data: &mut [f64],
) -> Result<(), String> {
    let _guard = lock_cgns();
    let c_name = std::ffi::CString::new(name)
        .map_err(|e| format!("invalid field name: {}", e))?;
    let status = unsafe {
        cg_field_read(
            fn_,
            base,
            zone,
            sol,
            c_name.as_ptr(),
            data_type,
            rmin.as_ptr(),
            rmax.as_ptr(),
            data.as_mut_ptr() as *mut std::ffi::c_void,
        )
    };
    status_to_result(status)
}
